### ISSUE TITLE
Version Tags

### ISSUE THREAD

**Issue by nathanhaigh** [csiro-crop-informatics/biokanga#1]
Any chance you can add version tags back in or did you lose/remove revesion history with the migration to GitHub?

Here's a todo list for the sake of record keeping:

# TODO List
- [x] Add in git tags for prior versions
- [x] Add github releases for prior versions
- [x] Update EasyBuild EasyConfigs for BioKanga releases, including URL and more recent versions

**Comment by alexwhan** [comment]
Definitely - still a work in progress, expect to see them in the next day or two. No history has been lost, but i'm doing some... curation... :)

**Comment by nathanhaigh** [comment]
Great - I should have looked through the commit history first! :) Can you create releases for each tag you create also? That was software package managers and the like have a non-git way to download the source.

Once this is done, I'll update the EasyBuild EasyConfigs for BioKanga: https://github.com/hpcugent/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/b/BioKanga

**Comment by alexwhan** [comment]
No problem

**Comment by alexwhan** [comment]
I've added tags for *some* previous versions. Note that these haven't been tested for successful building. In the next couple of days we'll do a 4.3.5 release that will incorporate the recent tidying and has at least had build tests

**Comment by nathanhaigh** [comment]
I've now created an EasyBuild easyconfig file for `v4.3.4`. I had to patch a couple of files, as you probably expect, to get the build to work: https://github.com/hpcugent/easybuild-easyconfigs/pull/4439.

**Comment by alexwhan** [comment]
great - i've been meaning to get a newer release sort (4.3.5) but haven't got to it yet. I'm hoping it should build without the patches...
